name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
       # node-version: [8.x, 10.x, 12.x]
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.HUAWEI_CLOUD }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: deploy-pages # The branch the action should deploy to.
        FOLDER: note
        BUILD_SCRIPT: npm install && npm install -g gitbook-cli && gitbook build .
